Generalize Thunderbird extension handling to cover Firefox

diff --git a/linuxclientsetup/scripts/client-config b/linuxclientsetup/scripts/client-config
--- a/linuxclientsetup/scripts/client-config
+++ b/linuxclientsetup/scripts/client-config
@@ -173,39 +173,50 @@ if ! karoshi-manage-flags get no_update_other >/dev/null; then
 fi
 
 #######################
-#Thunderbird extensions
+#Mozilla extensions
 #######################
 
-#{3550f703-e582-4d05-9a08-453d09bdfdc6} is the app-id for Thunderbird
-thunderbird_extensionsdir=/usr/lib/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6}
+# Mozilla app IDs
+declare -A mozilla_app_id=(
+	[firefox]="{ec8030f7-c20a-464f-9b0e-13a3a9e97384}"
+	[thunderbird]="{3550f703-e582-4d05-9a08-453d09bdfdc6}"
+)
 
 function do_xpi_raw {
 	xpi_name=$1
 	xpi_dir=$2
+	app=$3
 
-	if [[ ! -d $xpi_dir ]]; then
-		echo "Error: No such directory $xpi_dir" >&2
-		return 1
+	if [[ ! -d /opt/karoshi/mozilla/extensions/$xpi_name ]]; then
+		if [[ ! -d $xpi_dir ]]; then
+			echo "Error: No such directory $xpi_dir" >&2
+			return 1
+		fi
+
+		cp -rT "$xpi_dir" /opt/karoshi/mozilla/extensions/"$xpi_name"
 	fi
-
-	cp -rT "$xpi_dir" /opt/karoshi/thunderbird/extensions/"$xpi_name"
 
 	xpi_id=$(xmlstarlet sel -N rdf=http://www.w3.org/1999/02/22-rdf-syntax-ns# -N em=http://www.mozilla.org/2004/em-rdf# \
 				-t -m "//rdf:Description[@about='urn:mozilla:install-manifest']" -i "em:id" -v "em:id" --else -v "@em:id" \
-				/opt/karoshi/thunderbird/extensions/"$xpi_name"/install.rdf)
+				/opt/karoshi/mozilla/extensions/"$xpi_name"/install.rdf)
 	#Check if we actually have a valid extension id
 	if [[ -z $xpi_id ]]; then
-		echo "Warning: Thunderbird extension $xpi_name is invalid" >&2
+		echo "Warning: Mozilla extension $xpi_name is invalid" >&2
 		return
 	fi
 
 	#Install extension
-	ln -Ts /opt/karoshi/thunderbird/extensions/"$xpi_name" "$thunderbird_extensionsdir"/"$xpi_id"
+	app_id=${mozilla_app_id["$app"]}
+	if [[ ! -d /usr/lib/mozilla/extensions/"$app_id" ]]; then
+		mkdir -p /usr/lib/mozilla/extensions/"$app_id"
+	fi
+	ln -Ts /opt/karoshi/mozilla/extensions/"$xpi_name" /usr/lib/mozilla/extensions/"$app_id"/"$xpi_id"
 }
 
 function do_xpi {
 	xpi_name=$(basename "$1")
 	xpi_name=${xpi_name%.xpi}
+	app=$2
 
 	if [[ -z $xpi_name ]]; then
 		echo "Warning: Something bad happened" >&2
@@ -215,41 +226,51 @@ function do_xpi {
 	temp_dir=$(mktemp -d)
 
 	unzip -q "$1" -d "$temp_dir"
-	do_xpi_raw "$xpi_name" "$temp_dir"
+	do_xpi_raw "$xpi_name" "$temp_dir" "$app"
 
 	rm -rf "$temp_dir"
 }
 
-if [[ $MAILSERVER ]]; then
-	[[ -d $thunderbird_extensionsdir ]] || mkdir -p "$thunderbird_extensionsdir"
-	[[ -d /opt/karoshi/thunderbird/extensions ]] || mkdir -p /opt/karoshi/thunderbird/extensions
+[[ -d /opt/karoshi/mozilla/extensions ]] || mkdir -p /opt/karoshi/mozilla/extensions
+#Clear all extensions
+find /opt/karoshi/mozilla/extensions -mindepth 1 -delete
+find /usr/lib/mozilla/extensions/* -maxdepth 1 -lname '/opt/karoshi/mozilla/extensions/*' -delete
 
-	echo "Clearing current Thunderbird extensions"
-	#Clear all extensions
-	find /opt/karoshi/thunderbird/extensions -mindepth 1 -delete
-	find "$thunderbird_extensionsdir" -maxdepth 1 -lname '/opt/karoshi/thunderbird/extensions/*' -delete
+# Thunderbird
+if [[ $MAILSERVER ]]; then
+	# LEGACY compatibility
+	find /usr/lib/mozilla/extensions/"${mozilla_app_id[thunderbird]}" -maxdepth 1 -lname '/opt/karoshi/thunderbird/extensions/*' -delete
+	[[ -e /opt/karoshi/thunderbird/extensions ]] && rm -rf /opt/karoshi/thunderbird/extensions
 
 	timezone=$(< /etc/timezone)
 	mailserver_alias=$(< /tmp/netlogon/domain_information/aliases/"$MAILSERVER")
 
 	#Install SOGo
-	do_xpi_raw sogo-connector /opt/karoshi/linuxclientsetup/config-files/thunderbird/sogo-connector
-	do_xpi_raw sogo-integrator /opt/karoshi/linuxclientsetup/config-files/thunderbird/sogo-integrator
-	if [[ -d /opt/karoshi/thunderbird/extensions/sogo-integrator ]]; then
+	do_xpi_raw sogo-connector /opt/karoshi/linuxclientsetup/config-files/thunderbird/sogo-connector thunderbird
+	do_xpi_raw sogo-integrator /opt/karoshi/linuxclientsetup/config-files/thunderbird/sogo-integrator thunderbird
+	if [[ -d /opt/karoshi/mozilla/extensions/sogo-integrator ]]; then
 		sed -i "s@CHANGETHISTIMEZONE@$timezone@" \
-			/opt/karoshi/thunderbird/extensions/sogo-integrator/defaults/preferences/site.js
+			/opt/karoshi/mozilla/extensions/sogo-integrator/defaults/preferences/site.js
 		sed -i "s@CHANGETHISSOGO@$mailserver_alias.$DNSSUFFIX@" \
-			/opt/karoshi/thunderbird/extensions/sogo-integrator/chrome/content/extensions.rdf
+			/opt/karoshi/mozilla/extensions/sogo-integrator/chrome/content/extensions.rdf
 	fi
 	#Install Firetray
-	do_xpi_raw firetray /opt/karoshi/linuxclientsetup/config-files/thunderbird/firetray
+	do_xpi_raw firetray /opt/karoshi/linuxclientsetup/config-files/thunderbird/firetray thunderbird
 
 	if [[ -d /tmp/netlogon/linuxclient/$LINUX_VERSION/thunderbird/extensions ]]; then
 		while read -r -d $'\0' xpi; do
 			echo "Found new extension: $xpi"
-			do_xpi "$xpi"
+			do_xpi "$xpi" thunderbird
 		done < <(find /tmp/netlogon/linuxclient/$LINUX_VERSION/thunderbird/extensions -maxdepth 1 -mindepth 1 -name '*.xpi' -print0)
 	fi
+fi
+
+# Firefox
+if [[ -d /tmp/netlogon/linuxclient/$LINUX_VERSION/firefox/extensions ]]; then
+	while read -r -d $'\0' xpi; do
+		echo "Found new extension: $xpi"
+		do_xpi "$xpi" firefox
+	done < <(find /tmp/netlogon/linuxclient/$LINUX_VERSION/firefox/extensions -maxdepth 1 -mindepth 1 -name '*.xpi' -print0)
 fi
 
 ###########################
