Add ability to pull down Thunderbird extensions
Extensions should be put in netlogon/domain_information/thunderbird,
and must have the extension '.xpi'.

diff --git a/linuxclientsetup/scripts/client_config b/linuxclientsetup/scripts/client_config
--- a/linuxclientsetup/scripts/client_config
+++ b/linuxclientsetup/scripts/client_config
@@ -110,6 +110,41 @@ find /etc/skel -type d -print0 | xargs -0 chmod 755
 #Static ARPs
 [ -f /tmp/netlogon/domain_information/static_arps ] && arp -f /tmp/netlogon/domain_information/static_arps
 
+#######################
+#Thunderbird extensions
+#######################
+#{3550f703-e582-4d05-9a08-453d09bdfdc6} is the app-id for Thunderbird
+[ -d /usr/lib/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6} ] || mkdir -p /usr/lib/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6}
+[ -d /opt/karoshi/thunderbird/extensions ] || mkdir -p /opt/karoshi/thunderbird/extensions
+
+if [ -d /tmp/netlogon/domain_information/thunderbird ]; then
+	#Clear all extensions
+	find /opt/karoshi/thunderbird/extensions -mindepth 1 -maxdepth 1 -delete
+	
+	mkdir -p /tmp/thunderbird_xpi.$$
+	while read -r -d$'\0' xpi; do
+		xpi_name=$(basename "$xpi")
+		mkdir -p /tmp/thunderbird_xpi.$$/"$xpi_name"
+		unzip "$xpi" -d /tmp/thunderbird_xpi.$$/"$xpi_name"
+		
+		xpi_id=$(xmlstarlet sel -N rdf=http://www.w3.org/1999/02/22-rdf-syntax-ns# -N em=http://www.mozilla.org/2004/em-rdf# \
+					-t -v "//rdf:Description[@about='urn:mozilla:install-manifest']/em:id" /tmp/thunderbird_xpi.$$/"$xpi_name"/install.rdf)
+		#Check if we actually have a valid extension id
+		if ! [[ $xpi_id ]]; then
+			echo "Warning: Extension $xpi_name is invalid" >&2
+			continue
+		fi
+		
+		#Install extension
+		mv /tmp/thunderbird_xpi.$$/"$xpi_name" /opt/karoshi/thunderbird/extensions
+		ln -s /opt/karoshi/thunderbird/extensions/"$xpi_name" /usr/lib/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6}/"$xpi_id"
+	done < <(find /tmp/netlogon/domain_information/thunderbird -maxdepth 1 -mindepth 1 -name '*.xpi' -print0)
+	rm -rf /tmp/thunderbird_xpi.$$
+fi
+
+#Clear out old extensions
+find /usr/lib/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6} -maxdepth 1 -L -lname '/opt/karoshi/thunderbird/extensions/*' -delete
+
 ##########################
 #Update the upstart scripts
 ##########################
