Fix errors in Thunderbird extension code; remove need for temporary directory

diff --git a/linuxclientsetup/scripts/client_config b/linuxclientsetup/scripts/client_config
--- a/linuxclientsetup/scripts/client_config
+++ b/linuxclientsetup/scripts/client_config
@@ -116,19 +116,25 @@ find /etc/skel -type d -print0 | xargs -0 chmod 755
 
 function do_xpi {
 	xpi_name=$(basename "$1")
-	mkdir -p /tmp/thunderbird_xpi.$$/"$xpi_name"
-	unzip "$1" -d /tmp/thunderbird_xpi.$$/"$xpi_name"
+	xpi_name=${xpi_name%.xpi}
+	
+	if [[ -z $xpi_name ]]; then
+		echo "Warning: Something bad happened" >&2
+		return
+	fi
+	
+	mkdir /opt/karoshi/thunderbird/extensions/"$xpi_name"
+	unzip "$1" -d /opt/karoshi/thunderbird/extensions/"$xpi_name"
 	
 	xpi_id=$(xmlstarlet sel -N rdf=http://www.w3.org/1999/02/22-rdf-syntax-ns# -N em=http://www.mozilla.org/2004/em-rdf# \
-				-t -v "//rdf:Description[@about='urn:mozilla:install-manifest']/em:id" /tmp/thunderbird_xpi.$$/"$xpi_name"/install.rdf)
+				-t -v "//rdf:Description[@about='urn:mozilla:install-manifest']/em:id" /opt/karoshi/thunderbird/extensions/"$xpi_name"/install.rdf)
 	#Check if we actually have a valid extension id
-	if ! [[ $xpi_id ]]; then
-		echo "Warning: Extension $xpi_name is invalid" >&2
-		continue
+	if [[ -z $xpi_id ]]; then
+		echo "Warning: Thunderbird extension $xpi_name is invalid" >&2
+		return
 	fi
 	
 	#Install extension
-	mv /tmp/thunderbird_xpi.$$/"$xpi_name" /opt/karoshi/thunderbird/extensions
 	ln -s /opt/karoshi/thunderbird/extensions/"$xpi_name" /usr/lib/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6}/"$xpi_id"
 }
 
@@ -140,23 +146,20 @@ if [ -d /tmp/netlogon/domain_information/thunderbird/extensions ]; then
 	#Clear all extensions
 	find /opt/karoshi/thunderbird/extensions -mindepth 1 -maxdepth 1 -delete
 	
-	mkdir -p /tmp/thunderbird_xpi.$$
-	
 	#Global extensions
-	while read -r -d$'\0' xpi; do
+	while read -r -d $'\0' xpi; do
 		do_xpi "$xpi"
 	done < <(find /tmp/netlogon/domain_information/thunderbird/extensions -maxdepth 1 -mindepth 1 -name '*.xpi' -print0)
 	#Linux-specific extensions
 	if [ -d /tmp/netlogon/domain_information/thunderbird/extensions/linux-$(uname -i) ]; then
-		while read -r -d$'\0' xpi; do
+		while read -r -d $'\0' xpi; do
 			do_xpi "$xpi"
 		done < <(find /tmp/netlogon/domain_information/thunderbird/extensions/linux-$(uname -i) -maxdepth 1 -mindepth 1 -name '*.xpi' -print0)
 	fi
-	rm -rf /tmp/thunderbird_xpi.$$
 fi
 
 #Clear out old extensions
-find /usr/lib/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6} -maxdepth 1 -L -lname '/opt/karoshi/thunderbird/extensions/*' -delete
+find -L /usr/lib/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6} -maxdepth 1 -lname '/opt/karoshi/thunderbird/extensions/*' -delete
 
 ##########################
 #Update the upstart scripts
