Merge package changes to configuration files

diff --git a/configuration/etc/xdg/xfce4/xinitrc b/configuration/etc/xdg/xfce4/xinitrc
--- a/configuration/etc/xdg/xfce4/xinitrc
+++ b/configuration/etc/xdg/xfce4/xinitrc
@@ -1,13 +1,15 @@
 #!/bin/sh
 /opt/karoshi/linuxclientsetup/scripts/pre-session
 
+#!/bin/sh
+
 # fix broken $UID on some system...
 if test "x$UID" = "x"; then
-	if test -x /usr/xpg4/bin/id; then
-		UID=`/usr/xpg4/bin/id -u`;
-	else
-		UID=`id -u`;
-	fi
+  if test -x /usr/xpg4/bin/id; then
+    UID=`/usr/xpg4/bin/id -u`;
+  else
+    UID=`id -u`;
+  fi
 fi
 
 # set $XDG_MENU_PREFIX to "xfce-" so that "xfce-applications.menu" is picked
@@ -45,55 +47,20 @@ if test "x$XDG_CACHE_HOME" = "x" ; then
 fi
 [ -d "$XDG_CACHE_HOME" ] || mkdir "$XDG_CACHE_HOME"
 
-
 # set up XDG user directores.  see
 # http://freedesktop.org/wiki/Software/xdg-user-dirs
 if which xdg-user-dirs-update >/dev/null 2>&1; then
     xdg-user-dirs-update
 fi
 
-if test -f "$XDG_CONFIG_HOME/user-dirs.dirs"; then
-    . "$XDG_CONFIG_HOME/user-dirs.dirs"
-    # i'm deliberately not 'export'-ing the XDG_ vars, because you shouldn't
-    # rely on the env vars inside apps, since the file could be changed at
-    # any time by the user.  this is solely here for migration purposes.
-
-    # a bit of user dir migration...
-    if test -d "$HOME/Desktop" -a ! -L "$HOME/Desktop" \
-            -a "$XDG_DESKTOP_DIR" \
-            -a "$HOME/Desktop" != "$XDG_DESKTOP_DIR"
-    then
-        echo "Migrating $HOME/Desktop to $XDG_DESKTOP_DIR..."
-        test -d "$XDG_DESKTOP_DIR" && rmdir "$XDG_DESKTOP_DIR"
-        mv "$HOME/Desktop" "$XDG_DESKTOP_DIR" || echo "Desktop migration failed" >&2
-    fi
-
-    if test -d "$HOME/Templates" -a ! -L "$HOME/Templates" \
-            -a "$XDG_TEMPLATES_DIR" \
-            -a "$HOME/Templates" != "$XDG_TEMPLATES_DIR"
-    then
-        echo "Migrating $HOME/Templates to $XDG_TEMPLATES_DIR..."
-        test -d "$XDG_TEMPLATES_DIR" && rmdir "$XDG_TEMPLATES_DIR"
-        mv "$HOME/Templates" "$XDG_TEMPLATES_DIR" || echo "Templates migration failed" >&2
-    fi
-fi
-
-
 # Modify libglade and glade environment variables so that
 # it will find the files installed by Xfce
-LIBGLADE_MODULE_PATH="$LIBGLADE_MODULE_PATH:"
-GLADE_CATALOG_PATH="$GLADE_CATALOG_PATH:"
-GLADE_PIXMAP_PATH="$GLADE_PIXMAP_PATH:"
-GLADE_MODULE_PATH="$GLADE_MODULE_PATH:"
-export LIBGLADE_MODULE_PATH
+GLADE_CATALOG_PATH="$GLADE_CATALOG_PATH:/usr/share/glade3/catalogs"
+GLADE_PIXMAP_PATH="$GLADE_PIXMAP_PATH:/usr/lib/glade3/modules"
+GLADE_MODULE_PATH="$GLADE_MODULE_PATH:/usr/share/glade3/pixmaps"
 export GLADE_CATALOG_PATH
 export GLADE_PIXMAP_PATH
 export GLADE_MODULE_PATH
-
-# Export GTK_PATH so that GTK+ can find the Xfce theme engine
-# https://bugzilla.xfce.org/show_bug.cgi?id=7483
-#GTK_PATH="$GTK_PATH:/usr/lib/x86_64-linux-gnu/gtk-2.0"
-#export GTK_PATH
 
 # For now, start with an empty list
 XRESOURCES=""
@@ -123,111 +90,31 @@ cat /dev/null $XRESOURCES | xrdb -nocpp -merge -
 # load local modmap
 test -r $HOME/.Xmodmap && xmodmap $HOME/.Xmodmap
 
-# Use dbus-launch if installed.
-if test x"$DBUS_SESSION_BUS_ADDRESS" = x""; then
-    if which dbus-launch >/dev/null 2>&1; then
-		eval `dbus-launch --sh-syntax --exit-with-session`
-        # some older versions of dbus don't export the var properly
-        export DBUS_SESSION_BUS_ADDRESS
-    else
-        echo "Could not find dbus-launch; Xfce will not work properly" >&2
-	fi
-fi
-
-# launch gpg-agent or ssh-agent if enabled.
-ssh_agent_enabled=`xfconf-query -c xfce4-session -p /startup/ssh-agent/enabled 2> /dev/null`
-if test "$ssh_agent_enabled" != "false"; then
-    # if the user has pam_ssh installed, it will start ssh-agent for us, but
-    # of course won't start gpg-agent.  so, if ssh-agent is already running,
-    # but we want gpg-agent (and that's not running yet) start gpg-agent
-    # without ssh support
-
-    ssh_agent_type=`xfconf-query -c xfce4-session -p /startup/ssh-agent/type 2> /dev/null`
-    if test -z "$ssh_agent_type"; then
-        if which gpg-agent >/dev/null 2>&1; then
-            ssh_agent_type=gpg-agent
-        else
-            ssh_agent_type=ssh-agent
-        fi
-    fi
-
-    # ignore stale ssh-agents
-    if test "$SSH_AGENT_PID"; then
-        if ! kill -0 $SSH_AGENT_PID; then
-            unset SSH_AGENT_PID
-            unset SSH_AUTH_SOCK
-        fi
-    fi
-
-    case "$ssh_agent_type" in
-        gpg-agent)
-            if test -z "$SSH_AGENT_PID"; then
-                eval `gpg-agent --daemon --enable-ssh-support --write-env-file $XDG_CACHE_HOME/gpg-agent-info`
-                ssh_agent_kill_cmd="kill -INT $SSH_AGENT_PID; rm -f $XDG_CACHE_HOME/gpg-agent-info"
-            elif test -z "$GPG_AGENT_INFO"; then
-                echo "ssh-agent is already running; starting gpg-agent without ssh support"
-                eval `gpg-agent --daemon --write-env-file $XDG_CACHE_HOME/gpg-agent-info`
-                ssh_agent_kill_cmd="pkill -INT ^gpg-agent\$; rm -f $XDG_CACHE_HOME/gpg-agent-info"
-            else
-                echo "gpg-agent is already running"
-            fi
-            ;;
-
-        ssh-agent)
-            if test -z "$SSH_AGENT_PID"; then
-                eval `ssh-agent -s`
-                ssh_agent_kill_cmd="ssh-agent -s -k"
-            else
-                echo "ssh-agent is already running"
-            fi
-            ;;
-
-        *)
-            echo "Unrecognized agent type '$ssh_agent_type'" >&2
-            ;;
-    esac
-fi
-
-
-# launch a screensaver if enabled.  do not launch if we're root or if
-# we're in a VNC session.
-screensaver_enabled=`xfconf-query -c xfce4-session -p /startup/screensaver/enabled 2> /dev/null`
-if test $UID -gt 0 -a -z "$VNCSESSION" -a "$screensaver_enabled" != "false"; then
-    screensaver_type=`xfconf-query -c xfce4-session -p /startup/screensaver/type 2> /dev/null`
-
-    case "$screensaver_type" in
-        xscreensaver)
-            xscreensaver -no-splash &
-            ;;
-
-        gnome-screensaver)
-            gnome-screensaver &
-            ;;
-
-        *)
-            if test x"`which xscreensaver 2>/dev/null`" != x""; then
-                xscreensaver -no-splash &
-            elif test x"`which gnome-screensaver 2>/dev/null`" != x""; then
-                gnome-screensaver &
-            fi
-            ;;
-    esac
-fi
-
-
-# Run xfce4-session if installed
+# run xfce4-session if installed
 if which xfce4-session >/dev/null 2>&1; then
-    xfce4-session
-    /opt/karoshi/linuxclientsetup/scripts/post-session
 
-    if test "$ssh_agent_kill_cmd"; then
-        echo "running '$ssh_agent_kill_cmd'"
-        eval "$ssh_agent_kill_cmd"
+  # check if we start xfce4-session with ck-launch-session. this is only
+  # required for starting from a console, not a login manager
+  if test "x$XFCE4_SESSION_WITH_CK" = "x1"; then
+    if which ck-launch-session >/dev/null 2>&1; then
+      ck-launch-session xfce4-session
+    else
+      echo
+      echo "You have tried to start Xfce with consolekit support, but"
+      echo "ck-launch-session is not installed."
+      echo "Aborted startup..."
+      echo
+
+      exit 1
     fi
+  else
+    # start xfce4-session normally
+    xfce4-session
+  fi
+  /opt/karoshi/linuxclientsetup/scripts/post-session
 
-    exit 0
+  exit 0
 fi
-
 
 ##################
 # IMPORTANT NOTE #
@@ -241,6 +128,16 @@ fi
 
 ##################
 
+# Use dbus-launch if installed.
+if test x"$DBUS_SESSION_BUS_ADDRESS" = x""; then
+  if which dbus-launch >/dev/null 2>&1; then
+    eval `dbus-launch --sh-syntax --exit-with-session`
+    # some older versions of dbus don't export the var properly
+    export DBUS_SESSION_BUS_ADDRESS
+  else
+    echo "Could not find dbus-launch; Xfce will not work properly" >&2
+    fi
+fi
 
 # this is only necessary when running w/o xfce4-session
 xsetroot -solid black -cursor_name watch
@@ -250,9 +147,7 @@ xsetroot -solid black -cursor_name watch
 xfsettingsd &
 xfwm4 --daemon
 
-# start up stuff in $XDG_CONFIG_HOME/autostart/, as that looks to be
-# the new standard.  if that directory doesn't exist, try the old
-# ~/Desktop/Autostart method.  we're not going to do any migration here.
+# start up stuff in $XDG_CONFIG_HOME/autostart/
 if test -d "$XDG_CONFIG_HOME/autostart"; then
   for i in ${XDG_CONFIG_HOME}/autostart/*.desktop; do
     grep -q -E "^Hidden=true" "$i" && continue
@@ -271,12 +166,6 @@ if test -d "$XDG_CONFIG_HOME/autostart"; then
     cmd=`grep -E "^Exec=" "$i" | cut -d'=' -f2`
     if test "$cmd" && which "$cmd" >/dev/null 2>&1; then
       $cmd &
-    fi
-  done
-elif test -d "$HOME/Desktop/Autostart"; then
-  for i in `ls -1 -L ${HOME}/Desktop/Autostart/ 2>/dev/null`; do
-    if test -x $HOME/Desktop/Autostart/$i; then
-      $HOME/Desktop/Autostart/$i &
     fi
   done
 fi
@@ -309,9 +198,5 @@ EOF
 		done
 		;;
 esac
-
-if test "$ssh_agent_kill_cmd"; then
-	eval "$ssh_agent_kill_cmd"
-fi
 
 xsetroot -bg white -fg red  -solid black -cursor_name watch
