Fix Eclipse Mars installation (1/2).
As the Eclipse PPA is outdated (Eclipse 3.8 Juno) the script within this
commit will download, verify and install Eclipse Mars for amd64 and i386
architectures.
Commit 1 of 2.

diff --git a/clientsetup/buildclient/buildclient b/clientsetup/buildclient/buildclient
--- a/clientsetup/buildclient/buildclient
+++ b/clientsetup/buildclient/buildclient
@@ -2,12 +2,16 @@
 
 branch=pheonix
 
+# Import variables:
+# arch - containing architecture version
+# version - TODO
 source /tmp/setup_variables
+
 #Reboot the machine to auto log in to the karoshi user.
 REBOOT=yes
 
 #Main list of packages to install (apart from samba4 and SOGo which are compiled).
-packages="freshplayerplugin lightdm-kde-greeter mesa-utils libgl1-mesa-dev upstart-sysv unrar whois gtk2-engines atom shellcheck xorg bluegriffon xubuntu-desktop xfce4 indicator-application-gtk2 indicator-sound-gtk2 indicator-multiload xfce4-datetime-plugin xfce4-indicator-plugin xfce4-screenshooter xfce4-terminal xfce4-power-manager xubuntu-artwork shimmer-themes xubuntu-icon-theme thunar-archive-plugin thunar-media-tags-plugin catfish gnome-calculator gnome-system-monitor light-locker lightdm lightdm-gtk-greeter firefox flashplugin-installer thunderbird lightning-extension file-roller filezilla wireshark zenmap virtualbox geogebra stellarium kcolorchooser libreoffice libreoffice-mysql-connector libreoffice-lightproof-en wbritish gedit gedit-plugins scribus planner freemind ttf-dejavu ttf-mscorefonts-installer ttf-freefont dia blender gimp inkscape eog ardour jackd2 qjackctl a2jmidid hydrogen rosegarden musescore pavucontrol qsynth fluid-soundfont-gm lmms yoshimi lame stopmotion gtk-recordmydesktop openshot vlc brasero codeblocks eclipse glade netbeans git git-lfs default-jdk icedtea-plugin liblwjgl-java arduino tmux cups printer-driver-all openprinting-ppds cifs-utils libpam-mount krb5-user ntp xautolock yad gnupg ldap-utils synaptic xmlstarlet resolvconf iputils-ping iputils-tracepath iputils-arping net-tools mtr-tiny netcat-openbsd isc-dhcp-client libnss3-tools sssd virtualbox-guest-utils virtualbox-guest-x11 xserver-xorg-video-all wpasupplicant ssh-krb5 gksu zsh gvfs-backends pam-exec2 wine plymouth-x11 rsyslog unbound intltool nano netbeans-installer"
+packages="freshplayerplugin lightdm-kde-greeter mesa-utils libgl1-mesa-dev upstart-sysv unrar whois gtk2-engines atom shellcheck xorg bluegriffon xubuntu-desktop xfce4 indicator-application-gtk2 indicator-sound-gtk2 indicator-multiload xfce4-datetime-plugin xfce4-indicator-plugin xfce4-screenshooter xfce4-terminal xfce4-power-manager xubuntu-artwork shimmer-themes xubuntu-icon-theme thunar-archive-plugin thunar-media-tags-plugin catfish gnome-calculator gnome-system-monitor light-locker lightdm lightdm-gtk-greeter firefox flashplugin-installer thunderbird lightning-extension file-roller filezilla wireshark zenmap virtualbox geogebra stellarium kcolorchooser libreoffice libreoffice-mysql-connector libreoffice-lightproof-en wbritish gedit gedit-plugins scribus planner freemind ttf-dejavu ttf-mscorefonts-installer ttf-freefont dia blender gimp inkscape eog ardour jackd2 qjackctl a2jmidid hydrogen rosegarden musescore pavucontrol qsynth fluid-soundfont-gm lmms yoshimi lame stopmotion gtk-recordmydesktop openshot vlc brasero codeblocks glade netbeans git git-lfs default-jdk icedtea-plugin liblwjgl-java arduino tmux cups printer-driver-all openprinting-ppds cifs-utils libpam-mount krb5-user ntp xautolock yad gnupg ldap-utils synaptic xmlstarlet resolvconf iputils-ping iputils-tracepath iputils-arping net-tools mtr-tiny netcat-openbsd isc-dhcp-client libnss3-tools sssd virtualbox-guest-utils virtualbox-guest-x11 xserver-xorg-video-all wpasupplicant ssh-krb5 gksu zsh gvfs-backends pam-exec2 wine plymouth-x11 rsyslog unbound intltool nano netbeans-installer"
 
 #Utilities and other extras to install.
 extrapackages="shimmer-themes light-themes mate-icon-themes tango-icon-themes language-pack-ar libreoffice-l10n-ar language-pack-cs libreoffice-l10n-cs language-pack-da libreoffice-l10n-da language-pack-de libreoffice-l10n-de language-pack-el libreoffice-l10n-el language-pack-es libreoffice-l10n-es language-pack-en libreoffice-l10n-en-gb language-pack-fi libreoffice-l10n-fi language-pack-fr libreoffice-l10n-fr language-pack-he libreoffice-l10n-he language-pack-hi libreoffice-l10n-hi language-pack-id libreoffice-l10n-id language-pack-it libreoffice-l10n-it language-pack-ko libreoffice-l10n-ko language-pack-nb libreoffice-l10n-nb language-pack-nl libreoffice-l10n-nl language-pack-pl libreoffice-l10n-pl language-pack-pt libreoffice-l10n-pt language-pack-ru libreoffice-l10n-ru language-pack-sv libreoffice-l10n-sv language-pack-zh-hans-base libreoffice-l10n-zh-cn fonts-nanum-coding fonts-gargi myspell-en-gb"
@@ -32,63 +36,63 @@ apt-get install -y xinit
 
 apt-get install -y xubuntu-desktop
 
-# Get architecture version for reference when downloading packages
+##############################
+# ECLIPSE INSTALLATION
+##############################
 
-[ "$ARCH" == "" ] && echo -e "\nNo architecture present in chroot/opt/tmp/setup_variables.sh\n"
+# The eclipse PPA has not been updated since Eclipse 3.8 (Juno)
+# The following script will download, verify and install Eclipse Mars for amd64 and i386 architectures.
 
-# Checksum: a7ddf8be89d65e66dc09a54e98b47748  eclipse-java-mars-2-linux-gtk-x86_64.tar.gz
-# Checksum: 3f0460868e3702c6c8e6e346ae869f54  eclipse-java-mars-2-linux-gtk.tar.gz.
+# Checksum: a7ddf8be89d65e66dc09a54e98b47748  eclipse-java-mars-2-linux-gtk-x86_64.tar.gz (amd64)
+# Checksum: 3f0460868e3702c6c8e6e346ae869f54  eclipse-java-mars-2-linux-gtk.tar.gz. (i386)
 
-echo -e "\nAttempting to download eclipse."
-installEclipse="no"
-# Download eclipse
+echo "Begin Eclipse installation."
+
+eclipseDownload="no"
 if [ "$ARCH" == "amd64" ]; then
-	wget --timeout=10 -O $BUILDPATH/opt/tmp/eclipse-java-mars-2-linux-gtk-x86_64.tar.gz "http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/mars/2/eclipse-java-mars-2-linux-gtk-x86_64.tar.gz&r=1"
-	wgetOut=$?
-	if [ $wgetOut != 0 ]; then
-			# The download failed.
-			echo "There was a problem downloading eclipse, skipping."
-	fi
-
-	checksum=$(md5sum "$BUILDPATH/opt/tmp/eclipse-java-mars-2-linux-gtk-x86_64.tar.gz" | cut -d ' ' -f 1)
-	if [ "$checksum" != "a7ddf8be89d65e66dc09a54e98b47748" ]; then
-		echo "There was a problem validating the archive, skipping."
-	else
-		echo "Archive validated."
-		installEclipse="yes"
-	fi
+	echo "Architecture is ${ARCH}"
+	eclipsePath="/tmp/eclipse-java-mars-2-linux-gtk-x86_64.tar.gz"
+	eclipseFolder="/tmp/eclipse-java-mars-2-linux-gtk-x86_64"
+	eclipseURL="http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/mars/2/eclipse-java-mars-2-linux-gtk-x86_64.tar.gz&r=1"
+	eclipseDownload="yes"
+	eclipseChecksum="a7ddf8be89d65e66dc09a54e98b47748"
 elif [ "$ARCH" == "i386" ]; then
-	wget --timeout=10 -O $BUILDPATH/opt/tmp/eclipse-java-mars-2-linux-gtk.tar.gz "http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/mars/2/eclipse-java-mars-2-linux-gtk.tar.gz&r=1"
-	wgetOut=$?
-	if [ $wgetOut != 0 ]; then
-			# The download failed.
-			echo "There was a problem downloading eclipse, skipping."
+	echo "Architecture is ${ARCH}"
+	eclipsePath="/tmp/eclipse-java-mars-2-linux-gtk.tar.gz"
+	eclipseFolder="/tmp/eclipse-java-mars-2-linux-gtk"
+	eclipseURL="http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/mars/2/eclipse-java-mars-2-linux-gtk.tar.gz&r=1"
+	eclipseDownload="yes"
+	eclipseChecksum="3f0460868e3702c6c8e6e346ae869f54"
+else
+	echo "${ARCH} is not a supported architecture."
+fi
+
+eclipseInstall="no"
+if [ "$eclipseDownload" == "yes" ]; then
+	echo "Attempting to download Eclipse."
+	wget --timeout=10 -O $eclipsePath $eclipseURL
+	if [ $? != 0 ]; then
+			echo "There was a problem downloading Eclipse."
 	fi
 
-	checksum=$(md5sum "$BUILDPATH/opt/tmp/eclipse-java-mars-2-linux-gtk.tar.gz" | cut -d ' ' -f 1)
-	if [ "$checksum" != "3f0460868e3702c6c8e6e346ae869f54" ]; then
-		echo "There was a problem validating the archive, skipping."
+	if [ $(md5sum $eclipsePath | cut -d ' ' -f 1) == $eclipseChecksum ]; then
+		echo "Verified Eclipse download."
+		eclipseInstall="yes"
 	else
-		echo "Archive validated."
-		installEclipse="yes"
+		echo "eclipse download failed to validate."
 	fi
 fi
 
-if [ "$installEclipse" == "yes" ]; then
-	if [ "$ARCH" == "amd64" ]; then
-		echo -e "\nExtracting eclipse archive."
-		tar -zxvf $BUILDPATH/opt/tmp/eclipse-java-mars-2-linux-gtk-x86_64.tar.gz
-		echo -e "\nMoving eclipse into place."
-		mv $BUILDPATH/opt/tmp/eclipse-java-mars-2-linux-gtk-x86_64 /opt
-	fi
-	if [ "$ARCH" == "i386" ]; then
-		echo -e "\nExtracting eclipse archive."
-		tar -zxvf $BUILDPATH/opt/tmp/eclipse-java-mars-2-linux-gtk.tar.gz
-		echo -e "\nMoving eclipse into place."
-		mv $BUILDPATH/opt/tmp/eclipse-java-mars-2-linux-gtk.tar.gz /opt
-	fi
-	echo -e "\nEclipse installed."
+if [ "$eclipseInstall" == "yes" ]; then
+	echo "Attempting to install Eclipse."
+	echo "Extracting Eclipse archive."
+	tar -zxvf $eclipsePath
+	echo -e "Moving Eclipse into place."
+	mv $eclipseFolder /opt
+	echo -e "Eclipse installed."
 fi
+
+##############################
 
 # Install sources for kxstudio-team/ppa as its PPA is obselete
 # See http://kxstudio.linuxaudio.org/Repositories
