Karoshi Client translation support, fixes #23
l10n/update.sh generates l10n/karoshi-client.pot and all supported
language .po files. l10n/gtranslate.sh can run these files through Google
Translate, or the .po files can be translated by a human.

On installation, the .po files are converted into .mo files and put into the
correct places.

Ubiquity language selection and/or preseed will set the system locale

diff --git a/linuxclientsetup/utilities/setup b/linuxclientsetup/utilities/setup
--- a/linuxclientsetup/utilities/setup
+++ b/linuxclientsetup/utilities/setup
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-#Copyright (C) 2013 Robin McCorkell
+#Copyright (C) 2013,2014 Robin McCorkell
 
 #This file is part of Karoshi Client.
 #
@@ -30,8 +30,8 @@ then
 fi
 
 if [[ $EUID -ne 0 ]]; then
-	echo "ERROR: Must be running as effective root" >&2
-	info_alert "Privilage Error" "This script must be run as root"
+	echo $"This script must be run as root" >&2
+	info_alert $"Karoshi Setup" $"This script must be run as root"
 	exit 1
 fi
 
@@ -152,8 +152,8 @@ if [[ -e /usr/bin/dumpcap ]]; then
 	if which setcap > /dev/null ; then
 		chmod u=rwx,g=rx,o=r /usr/bin/dumpcap
 		if ! setcap cap_net_raw,cap_net_admin=eip /usr/bin/dumpcap; then
-			echo "Setting capabilities for dumpcap using Linux Capabilities failed."
-			echo "Falling back to setting set-user-id bit."
+			echo $"Setting capabilities for dumpcap using Linux Capabilities failed."
+			echo $"Falling back to setting set-user-id bit."
 			chmod u=rwxs,g=rx,o=r /usr/bin/dumpcap
 		fi
 	else
