Extend PAM exit codes to virtualbox-mkdir

diff --git a/linuxclientsetup/utilities/virtualbox-mkdir b/linuxclientsetup/utilities/virtualbox-mkdir
--- a/linuxclientsetup/utilities/virtualbox-mkdir
+++ b/linuxclientsetup/utilities/virtualbox-mkdir
@@ -19,17 +19,27 @@
 #
 #Website: http://www.karoshi.org.uk
 
+if [[ ! $PAM_USER ]]; then
+	echo "ERROR: Must be run through pam_exec.so" >&2
+	exit $PAM_CRED_UNAVAIL
+fi
+#Make sure the user exists
+if ! getent passwd "$PAM_USER" >/dev/null; then
+	echo "ERROR: Must be run with a valid PAM_USER" >&2
+	exit $PAM_USER_UNKNOWN
+fi
+
 virtualbox_path="/opt/virtualbox"
 user_info=$(getent passwd "$PAM_USER")
 user_uid=$(cut -d":" -f3 <<< "$user_info")
 user_gid=$(cut -d":" -f4 <<< "$user_info")
 user_home=$(cut -d":" -f6 <<< "$user_info")
 
-echo "`date`: karoshi-virtualbox-mkdir for $PAM_USER"
+echo "$0 for $PAM_USER"
 
-if ! [[ -d $user_home/network/home ]]; then
+if ! [[ $user_uid -ge 1000 ]]; then
 	echo "User is not a domain user - exiting"
-	exit 0
+	exit $PAM_IGNORE
 fi
 
 if [[ ! -d $virtualbox_path ]]; then
@@ -75,4 +85,4 @@ else
 	echo "'$user_home/VirtualBox VMs' already exists! Not creating symlink"
 fi
 
-exit 0
+exit $PAM_SUCCESS
