Move virtualbox-mkdir code to PAM
Having PAM do the work setting up a directory for the user reduces the
privilages required for the user. Logging can also be done more effectively.

diff --git a/linuxclientsetup/utilities/virtualbox-mkdir b/linuxclientsetup/utilities/virtualbox-mkdir
--- a/linuxclientsetup/utilities/virtualbox-mkdir
+++ b/linuxclientsetup/utilities/virtualbox-mkdir
@@ -1,40 +1,70 @@
 #!/bin/bash
 
 if [[ $EUID -ne 0 ]]; then
-	echo "ERROR: Must be run as root!" >&2
+	echo "ERROR: Must be run as root" >&2
 	exit 1
 fi
-if [ ! "$SUDO_USER" ]; then
-	echo "ERROR: Must be run under sudo!" >&2
+if [[ ! $PAM_USER ]]; then
+	echo "ERROR: Must be run through pam_exec.so" >&2
 	exit 1
 fi
+
+[[ $PAM_TYPE == open_session ]] || exit 0
 
 virtualbox_path="/opt/virtualbox"
-user_home=$(getent passwd "$SUDO_USER" | cut -d":" -f6)
+user_info=$(getent passwd "$PAM_USER")
+user_uid=$(cut -d":" -f3 <<< "$user_info")
+user_gid=$(cut -d":" -f4 <<< "$user_info")
+user_home=$(cut -d":" -f6 <<< "$user_info")
 
-if [ ! -d "$virtualbox_path" ]; then
+echo "`date`: karoshi-virtualbox-mkdir for $PAM_USER"
+
+if ! [[ -d $user_home/network/home ]]; then
+	echo "User is not a domain user - exiting"
+	exit 0
+fi
+
+if [[ ! -d $virtualbox_path ]]; then
+	echo "$virtualbox_path did not exist - creating"
 	mkdir -p "$virtualbox_path" -m 0755
 fi
-if [ ! -d "$virtualbox_path"/isos ]; then
+if [[ ! -d $virtualbox_path/isos ]]; then
+	echo "$virtualbox_path/isos did not exist - creating"
 	mkdir "$virtualbox_path"/isos -m 1777
 fi
-if [ ! -d "$virtualbox_path"/users ]; then
+if [[ ! -d $virtualbox_path/users ]]; then
+	echo "$virtualbox_path/users did not exist - creating"
 	mkdir "$virutalbox_path"/users -m 0755
 fi
 
 function make_virtualbox_dir {
-	mkdir "$virtualbox_path"/users/"$SUDO_USER" -m 0700
-	chown $SUDO_UID:$SUDO_GID "$virtualbox_path"/users/"$SUDO_USER"
+	echo "Creating user folder: '$virtualbox_path/users/$PAM_USER'"
+	mkdir "$virtualbox_path"/users/"$PAM_USER" -m 0700
+	chown $user_uid:$user_gid "$virtualbox_path"/users/"$PAM_USER"
 }
 
-if [ ! -d "$virtualbox_path"/users/"$SUDO_USER" ]; then
+if [[ ! -d $virtualbox_path/users/$PAM_USER ]]; then
 	make_virtualbox_dir
 fi
 
-if [[ $(stat -c %U "$virtualbox_path"/users/"$SUDO_USER") != $SUDO_USER ]]; then
-	[ -e "$virtualbox_path"/users/"$SUDO_USER".old ] && rm -rf "$virtualbox_path"/users/"$SUDO_USER".old
-	mv "$virtualbox_path"/users/"$SUDO_USER" "$virtualbox_path"/users/"$SUDO_USER".old
+folder_owner=$(stat -c %U "$virtualbox_path"/users/"$PAM_USER")
+if [[ $folder_owner != $PAM_USER ]]; then
+	echo "Incorrect owner of user folder: $folder_owner"
+	echo "Moving '$virtualbox_path/users/$PAM_USER' to '$virtualbox_path/users/$PAM_USER.old'"
+	[[ -e $virtualbox_path/users/$PAM_USER.old ]] && rm -rf "$virtualbox_path"/users/"$PAM_USER".old
+	mv "$virtualbox_path"/users/"$PAM_USER" "$virtualbox_path"/users/"$PAM_USER".old
 	make_virtualbox_dir
 fi
 
-echo "$virtualbox_path"/users/"$SUDO_USER"
+if ! [[ -e $user_home/.VirtualBox ]]; then
+	ln -sf "$virtualbox_path"/users/"$PAM_USER" "$user_home"/.VirtualBox
+else
+	echo "'$user_home/.VirtualBox' already exists! Not creating symlink"
+fi
+if ! [[ -e $user_home/VirtualBox VMs ]]; then
+	ln -sf "$virtualbox_path"/users/"$PAM_USER" "$user_home"/"VirtualBox VMs"
+else
+	echo "'$user_home/VirtualBox VMs' already exists! Not creating symlink"
+fi
+
+exit 0
